version: '3.7'
networks:
  banco:
services:
  platform-builders:
    build:
      dockerfile: ./Dockerfile
      context: ..
    container_name: "cadastro-cliente"
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgres
    networks:
      - banco
  postgres:
    image: "postgres:9.5.16-alpine"
    ports:
      - "5432:5432"
    restart: always
    container_name: "platformbuilders_db"
    environment:
      - POSTGRES_DB=platformbuilders
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - platform_builders_postgres:/var/lib/postgresql/data
    networks:
      - banco
  flyway:
    container_name: platformbuilders_flyway
    image: "flyway/flyway"
    command: -configFiles=flyway.conf migrate
    volumes:
      - platform_builders_postgres:/var/lib/platformbuilders_flyway/data/
      - ./conf/flyway.conf:/flyway/flyway.conf
      - ./sql:/flyway/sql
    depends_on:
      - postgres
    networks:
      - banco
volumes:
  platform_builders_postgres: